import type {BranchConcreteSyntaxTreeNode} from "../../../BranchConcreteSyntaxTreeNode.ts";
import type {FunctionHeaderUnknownSegmentContentConcreteSyntaxTreeNodeDataChildren} from "./FunctionHeaderUnknownSegmentContentConcreteSyntaxTreeNodeDataChildren.ts";
import type {functionHeaderUnknownSegmentContentConcreteSyntaxTreeNodeKindName} from "./functionHeaderUnknownSegmentContentConcreteSyntaxTreeNodeKindName.ts";
export type FunctionHeaderUnknownSegmentContentConcreteSyntaxTreeNode =
	BranchConcreteSyntaxTreeNode<
		typeof functionHeaderUnknownSegmentContentConcreteSyntaxTreeNodeKindName,
		FunctionHeaderUnknownSegmentContentConcreteSyntaxTreeNodeDataChildren
	>;
