import type {TerminalAtom} from "../../../../atom/implementations/terminal/TerminalAtom.ts";
import type {WordCharacter} from "../../../../character/implementations/word/WordCharacter.ts";
export type WordCharacterConcreteSyntaxTreeNodeAtom =
	| TerminalAtom<"0">
	| TerminalAtom<"1">
	| TerminalAtom<"2">
	| TerminalAtom<"3">
	| TerminalAtom<"4">
	| TerminalAtom<"5">
	| TerminalAtom<"6">
	| TerminalAtom<"7">
	| TerminalAtom<"8">
	| TerminalAtom<"9">
	| TerminalAtom<"!">
	| TerminalAtom<"#">
	| TerminalAtom<"$">
	| TerminalAtom<"%">
	| TerminalAtom<"&">
	| TerminalAtom<"*">
	| TerminalAtom<"+">
	| TerminalAtom<"-">
	| TerminalAtom<"/">
	| TerminalAtom<":">
	| TerminalAtom<";">
	| TerminalAtom<"<">
	| TerminalAtom<"=">
	| TerminalAtom<">">
	| TerminalAtom<"?">
	| TerminalAtom<"@">
	| TerminalAtom<"^">
	| TerminalAtom<"_">
	| TerminalAtom<"A">
	| TerminalAtom<"a">
	| TerminalAtom<"B">
	| TerminalAtom<"b">
	| TerminalAtom<"C">
	| TerminalAtom<"c">
	| TerminalAtom<"D">
	| TerminalAtom<"d">
	| TerminalAtom<"E">
	| TerminalAtom<"e">
	| TerminalAtom<"F">
	| TerminalAtom<"f">
	| TerminalAtom<"G">
	| TerminalAtom<"g">
	| TerminalAtom<"H">
	| TerminalAtom<"h">
	| TerminalAtom<"I">
	| TerminalAtom<"i">
	| TerminalAtom<"J">
	| TerminalAtom<"j">
	| TerminalAtom<"K">
	| TerminalAtom<"k">
	| TerminalAtom<"L">
	| TerminalAtom<"l">
	| TerminalAtom<"M">
	| TerminalAtom<"m">
	| TerminalAtom<"N">
	| TerminalAtom<"n">
	| TerminalAtom<"O">
	| TerminalAtom<"o">
	| TerminalAtom<"P">
	| TerminalAtom<"p">
	| TerminalAtom<"Q">
	| TerminalAtom<"q">
	| TerminalAtom<"R">
	| TerminalAtom<"r">
	| TerminalAtom<"S">
	| TerminalAtom<"s">
	| TerminalAtom<"T">
	| TerminalAtom<"t">
	| TerminalAtom<"U">
	| TerminalAtom<"u">
	| TerminalAtom<"V">
	| TerminalAtom<"v">
	| TerminalAtom<"W">
	| TerminalAtom<"w">
	| TerminalAtom<"X">
	| TerminalAtom<"x">
	| TerminalAtom<"Y">
	| TerminalAtom<"y">
	| TerminalAtom<"Z">
	| TerminalAtom<"z">;
