import type {BranchConcreteSyntaxTreeNode} from "../../../BranchConcreteSyntaxTreeNode.ts";
import type {FunctionHeaderKnownStartingSegmentsConcreteSyntaxTreeNodeDataChildren} from "./FunctionHeaderKnownStartingSegmentsConcreteSyntaxTreeNodeDataChildren.ts";
import type {functionHeaderKnownStartingSegmentsConcreteSyntaxTreeNodeKindName} from "./functionHeaderKnownStartingSegmentsConcreteSyntaxTreeNodeKindName.ts";
export type FunctionHeaderKnownStartingSegmentsConcreteSyntaxTreeNode =
	BranchConcreteSyntaxTreeNode<
		typeof functionHeaderKnownStartingSegmentsConcreteSyntaxTreeNodeKindName,
		FunctionHeaderKnownStartingSegmentsConcreteSyntaxTreeNodeDataChildren
	>;
