import {wordCharacterRuleName} from "./name/wordCharacterRuleName.ts";
import {WordCharacterConcreteSyntaxTreeNode} from "../../../concrete-syntax-tree-node/implementations/word-character/WordCharacterConcreteSyntaxTreeNode.ts";
import type {WordCharacterConcreteSyntaxTreeNodeAtom} from "../../../concrete-syntax-tree-node/implementations/word-character/atom/WordCharacterConcreteSyntaxTreeNodeAtom.ts";
import {TerminalExpression} from "../../../expression/implementations/terminal/TerminalExpression.ts";
import type {RuleById} from "../../../rule-by-id/RuleById.ts";
import {Rule} from "../../Rule.ts";
export class WordCharacterRule extends Rule<
	WordCharacterConcreteSyntaxTreeNodeAtom,
	WordCharacterConcreteSyntaxTreeNode
> {
	public constructor() {
		super(wordCharacterRuleName);
	}
	public override buildNode(
		atom: WordCharacterConcreteSyntaxTreeNodeAtom,
	): WordCharacterConcreteSyntaxTreeNode {
		const node = new WordCharacterConcreteSyntaxTreeNode(atom);
		return node;
	}
	public override getRightExpressions(
		ruleById: RuleById,
	): readonly [
		TerminalExpression<"0">,
		TerminalExpression<"1">,
		TerminalExpression<"2">,
		TerminalExpression<"3">,
		TerminalExpression<"4">,
		TerminalExpression<"5">,
		TerminalExpression<"6">,
		TerminalExpression<"7">,
		TerminalExpression<"8">,
		TerminalExpression<"9">,
		TerminalExpression<"!">,
		TerminalExpression<"#">,
		TerminalExpression<"$">,
		TerminalExpression<"%">,
		TerminalExpression<"&">,
		TerminalExpression<"*">,
		TerminalExpression<"+">,
		TerminalExpression<",">,
		TerminalExpression<"-">,
		TerminalExpression<".">,
		TerminalExpression<"/">,
		TerminalExpression<":">,
		TerminalExpression<";">,
		TerminalExpression<"<">,
		TerminalExpression<"=">,
		TerminalExpression<">">,
		TerminalExpression<"?">,
		TerminalExpression<"@">,
		TerminalExpression<"^">,
		TerminalExpression<"_">,
		TerminalExpression<"A">,
		TerminalExpression<"a">,
		TerminalExpression<"B">,
		TerminalExpression<"b">,
		TerminalExpression<"C">,
		TerminalExpression<"c">,
		TerminalExpression<"D">,
		TerminalExpression<"d">,
		TerminalExpression<"E">,
		TerminalExpression<"e">,
		TerminalExpression<"F">,
		TerminalExpression<"f">,
		TerminalExpression<"G">,
		TerminalExpression<"g">,
		TerminalExpression<"H">,
		TerminalExpression<"h">,
		TerminalExpression<"I">,
		TerminalExpression<"i">,
		TerminalExpression<"J">,
		TerminalExpression<"j">,
		TerminalExpression<"K">,
		TerminalExpression<"k">,
		TerminalExpression<"L">,
		TerminalExpression<"l">,
		TerminalExpression<"M">,
		TerminalExpression<"m">,
		TerminalExpression<"N">,
		TerminalExpression<"n">,
		TerminalExpression<"O">,
		TerminalExpression<"o">,
		TerminalExpression<"P">,
		TerminalExpression<"p">,
		TerminalExpression<"Q">,
		TerminalExpression<"q">,
		TerminalExpression<"R">,
		TerminalExpression<"r">,
		TerminalExpression<"S">,
		TerminalExpression<"s">,
		TerminalExpression<"T">,
		TerminalExpression<"t">,
		TerminalExpression<"U">,
		TerminalExpression<"u">,
		TerminalExpression<"V">,
		TerminalExpression<"v">,
		TerminalExpression<"W">,
		TerminalExpression<"w">,
		TerminalExpression<"X">,
		TerminalExpression<"x">,
		TerminalExpression<"Y">,
		TerminalExpression<"y">,
		TerminalExpression<"Z">,
		TerminalExpression<"z">,
	] {
		const rightExpressions: readonly [
			TerminalExpression<"0">,
			TerminalExpression<"1">,
			TerminalExpression<"2">,
			TerminalExpression<"3">,
			TerminalExpression<"4">,
			TerminalExpression<"5">,
			TerminalExpression<"6">,
			TerminalExpression<"7">,
			TerminalExpression<"8">,
			TerminalExpression<"9">,
			TerminalExpression<"!">,
			TerminalExpression<"#">,
			TerminalExpression<"$">,
			TerminalExpression<"%">,
			TerminalExpression<"&">,
			TerminalExpression<"*">,
			TerminalExpression<"+">,
			TerminalExpression<",">,
			TerminalExpression<"-">,
			TerminalExpression<".">,
			TerminalExpression<"/">,
			TerminalExpression<":">,
			TerminalExpression<";">,
			TerminalExpression<"<">,
			TerminalExpression<"=">,
			TerminalExpression<">">,
			TerminalExpression<"?">,
			TerminalExpression<"@">,
			TerminalExpression<"^">,
			TerminalExpression<"_">,
			TerminalExpression<"A">,
			TerminalExpression<"a">,
			TerminalExpression<"B">,
			TerminalExpression<"b">,
			TerminalExpression<"C">,
			TerminalExpression<"c">,
			TerminalExpression<"D">,
			TerminalExpression<"d">,
			TerminalExpression<"E">,
			TerminalExpression<"e">,
			TerminalExpression<"F">,
			TerminalExpression<"f">,
			TerminalExpression<"G">,
			TerminalExpression<"g">,
			TerminalExpression<"H">,
			TerminalExpression<"h">,
			TerminalExpression<"I">,
			TerminalExpression<"i">,
			TerminalExpression<"J">,
			TerminalExpression<"j">,
			TerminalExpression<"K">,
			TerminalExpression<"k">,
			TerminalExpression<"L">,
			TerminalExpression<"l">,
			TerminalExpression<"M">,
			TerminalExpression<"m">,
			TerminalExpression<"N">,
			TerminalExpression<"n">,
			TerminalExpression<"O">,
			TerminalExpression<"o">,
			TerminalExpression<"P">,
			TerminalExpression<"p">,
			TerminalExpression<"Q">,
			TerminalExpression<"q">,
			TerminalExpression<"R">,
			TerminalExpression<"r">,
			TerminalExpression<"S">,
			TerminalExpression<"s">,
			TerminalExpression<"T">,
			TerminalExpression<"t">,
			TerminalExpression<"U">,
			TerminalExpression<"u">,
			TerminalExpression<"V">,
			TerminalExpression<"v">,
			TerminalExpression<"W">,
			TerminalExpression<"w">,
			TerminalExpression<"X">,
			TerminalExpression<"x">,
			TerminalExpression<"Y">,
			TerminalExpression<"y">,
			TerminalExpression<"Z">,
			TerminalExpression<"z">,
		] = [
			new TerminalExpression<"0">("0"),
			new TerminalExpression<"1">("1"),
			new TerminalExpression<"2">("2"),
			new TerminalExpression<"3">("3"),
			new TerminalExpression<"4">("4"),
			new TerminalExpression<"5">("5"),
			new TerminalExpression<"6">("6"),
			new TerminalExpression<"7">("7"),
			new TerminalExpression<"8">("8"),
			new TerminalExpression<"9">("9"),
			new TerminalExpression<"!">("!"),
			new TerminalExpression<"#">("#"),
			new TerminalExpression<"$">("$"),
			new TerminalExpression<"%">("%"),
			new TerminalExpression<"&">("&"),
			new TerminalExpression<"*">("*"),
			new TerminalExpression<"+">("+"),
			new TerminalExpression<",">(","),
			new TerminalExpression<"-">("-"),
			new TerminalExpression<".">("."),
			new TerminalExpression<"/">("/"),
			new TerminalExpression<":">(":"),
			new TerminalExpression<";">(";"),
			new TerminalExpression<"<">("<"),
			new TerminalExpression<"=">("="),
			new TerminalExpression<">">(">"),
			new TerminalExpression<"?">("?"),
			new TerminalExpression<"@">("@"),
			new TerminalExpression<"^">("^"),
			new TerminalExpression<"_">("_"),
			new TerminalExpression<"A">("A"),
			new TerminalExpression<"a">("a"),
			new TerminalExpression<"B">("B"),
			new TerminalExpression<"b">("b"),
			new TerminalExpression<"C">("C"),
			new TerminalExpression<"c">("c"),
			new TerminalExpression<"D">("D"),
			new TerminalExpression<"d">("d"),
			new TerminalExpression<"E">("E"),
			new TerminalExpression<"e">("e"),
			new TerminalExpression<"F">("F"),
			new TerminalExpression<"f">("f"),
			new TerminalExpression<"G">("G"),
			new TerminalExpression<"g">("g"),
			new TerminalExpression<"H">("H"),
			new TerminalExpression<"h">("h"),
			new TerminalExpression<"I">("I"),
			new TerminalExpression<"i">("i"),
			new TerminalExpression<"J">("J"),
			new TerminalExpression<"j">("j"),
			new TerminalExpression<"K">("K"),
			new TerminalExpression<"k">("k"),
			new TerminalExpression<"L">("L"),
			new TerminalExpression<"l">("l"),
			new TerminalExpression<"M">("M"),
			new TerminalExpression<"m">("m"),
			new TerminalExpression<"N">("N"),
			new TerminalExpression<"n">("n"),
			new TerminalExpression<"O">("O"),
			new TerminalExpression<"o">("o"),
			new TerminalExpression<"P">("P"),
			new TerminalExpression<"p">("p"),
			new TerminalExpression<"Q">("Q"),
			new TerminalExpression<"q">("q"),
			new TerminalExpression<"R">("R"),
			new TerminalExpression<"r">("r"),
			new TerminalExpression<"S">("S"),
			new TerminalExpression<"s">("s"),
			new TerminalExpression<"T">("T"),
			new TerminalExpression<"t">("t"),
			new TerminalExpression<"U">("U"),
			new TerminalExpression<"u">("u"),
			new TerminalExpression<"V">("V"),
			new TerminalExpression<"v">("v"),
			new TerminalExpression<"W">("W"),
			new TerminalExpression<"w">("w"),
			new TerminalExpression<"X">("X"),
			new TerminalExpression<"x">("x"),
			new TerminalExpression<"Y">("Y"),
			new TerminalExpression<"y">("y"),
			new TerminalExpression<"Z">("Z"),
			new TerminalExpression<"z">("z"),
		];
		return rightExpressions;
	}
}
