import {VariableNameCharacterConcreteSyntaxTreeNode} from "../../../concrete-syntax-tree-node/implementations/variable-name-character/VariableNameCharacterConcreteSyntaxTreeNode.ts";
import type {VariableNameCharacterConcreteSyntaxTreeNodeAtom} from "../../../concrete-syntax-tree-node/implementations/variable-name-character/atom/VariableNameCharacterConcreteSyntaxTreeNodeAtom.ts";
import {TerminalExpression} from "../../../expression/implementations/terminal/TerminalExpression.ts";
import type {RuleById} from "../../../rule-by-id/RuleById.ts";
import {Rule} from "../../Rule.ts";
export class VariableNameCharacterRule extends Rule<VariableNameCharacterConcreteSyntaxTreeNode> {
	public constructor() {
		super("VariableNameCharacter");
	}
	public override buildNode(
		atom: VariableNameCharacterConcreteSyntaxTreeNodeAtom,
	): VariableNameCharacterConcreteSyntaxTreeNode {
		const node = new VariableNameCharacterConcreteSyntaxTreeNode(atom);
		return node;
	}
	public override getRightExpressions(
		ruleById: RuleById,
	): readonly [
		TerminalExpression<"!">,
		TerminalExpression<"#">,
		TerminalExpression<"$">,
		TerminalExpression<"%">,
		TerminalExpression<"&">,
		TerminalExpression<"*">,
		TerminalExpression<"+">,
		TerminalExpression<",">,
		TerminalExpression<"-">,
		TerminalExpression<".">,
		TerminalExpression<"/">,
		TerminalExpression<"0">,
		TerminalExpression<"1">,
		TerminalExpression<"2">,
		TerminalExpression<"3">,
		TerminalExpression<"4">,
		TerminalExpression<"5">,
		TerminalExpression<"6">,
		TerminalExpression<"7">,
		TerminalExpression<"8">,
		TerminalExpression<"9">,
		TerminalExpression<":">,
		TerminalExpression<";">,
		TerminalExpression<"<">,
		TerminalExpression<"=">,
		TerminalExpression<">">,
		TerminalExpression<"?">,
		TerminalExpression<"@">,
		TerminalExpression<"A">,
		TerminalExpression<"B">,
		TerminalExpression<"C">,
		TerminalExpression<"D">,
		TerminalExpression<"E">,
		TerminalExpression<"F">,
		TerminalExpression<"G">,
		TerminalExpression<"H">,
		TerminalExpression<"I">,
		TerminalExpression<"J">,
		TerminalExpression<"K">,
		TerminalExpression<"L">,
		TerminalExpression<"M">,
		TerminalExpression<"N">,
		TerminalExpression<"O">,
		TerminalExpression<"P">,
		TerminalExpression<"Q">,
		TerminalExpression<"R">,
		TerminalExpression<"S">,
		TerminalExpression<"T">,
		TerminalExpression<"U">,
		TerminalExpression<"V">,
		TerminalExpression<"W">,
		TerminalExpression<"X">,
		TerminalExpression<"Y">,
		TerminalExpression<"Z">,
		TerminalExpression<"^">,
		TerminalExpression<"_">,
		TerminalExpression<"a">,
		TerminalExpression<"b">,
		TerminalExpression<"c">,
		TerminalExpression<"d">,
		TerminalExpression<"e">,
		TerminalExpression<"f">,
		TerminalExpression<"g">,
		TerminalExpression<"h">,
		TerminalExpression<"i">,
		TerminalExpression<"j">,
		TerminalExpression<"k">,
		TerminalExpression<"l">,
		TerminalExpression<"m">,
		TerminalExpression<"n">,
		TerminalExpression<"o">,
		TerminalExpression<"p">,
		TerminalExpression<"q">,
		TerminalExpression<"r">,
		TerminalExpression<"s">,
		TerminalExpression<"t">,
		TerminalExpression<"u">,
		TerminalExpression<"v">,
		TerminalExpression<"w">,
		TerminalExpression<"x">,
		TerminalExpression<"y">,
		TerminalExpression<"z">,
	] {
		const rightExpressions: readonly [
			TerminalExpression<"!">,
			TerminalExpression<"#">,
			TerminalExpression<"$">,
			TerminalExpression<"%">,
			TerminalExpression<"&">,
			TerminalExpression<"*">,
			TerminalExpression<"+">,
			TerminalExpression<",">,
			TerminalExpression<"-">,
			TerminalExpression<".">,
			TerminalExpression<"/">,
			TerminalExpression<"0">,
			TerminalExpression<"1">,
			TerminalExpression<"2">,
			TerminalExpression<"3">,
			TerminalExpression<"4">,
			TerminalExpression<"5">,
			TerminalExpression<"6">,
			TerminalExpression<"7">,
			TerminalExpression<"8">,
			TerminalExpression<"9">,
			TerminalExpression<":">,
			TerminalExpression<";">,
			TerminalExpression<"<">,
			TerminalExpression<"=">,
			TerminalExpression<">">,
			TerminalExpression<"?">,
			TerminalExpression<"@">,
			TerminalExpression<"A">,
			TerminalExpression<"B">,
			TerminalExpression<"C">,
			TerminalExpression<"D">,
			TerminalExpression<"E">,
			TerminalExpression<"F">,
			TerminalExpression<"G">,
			TerminalExpression<"H">,
			TerminalExpression<"I">,
			TerminalExpression<"J">,
			TerminalExpression<"K">,
			TerminalExpression<"L">,
			TerminalExpression<"M">,
			TerminalExpression<"N">,
			TerminalExpression<"O">,
			TerminalExpression<"P">,
			TerminalExpression<"Q">,
			TerminalExpression<"R">,
			TerminalExpression<"S">,
			TerminalExpression<"T">,
			TerminalExpression<"U">,
			TerminalExpression<"V">,
			TerminalExpression<"W">,
			TerminalExpression<"X">,
			TerminalExpression<"Y">,
			TerminalExpression<"Z">,
			TerminalExpression<"^">,
			TerminalExpression<"_">,
			TerminalExpression<"a">,
			TerminalExpression<"b">,
			TerminalExpression<"c">,
			TerminalExpression<"d">,
			TerminalExpression<"e">,
			TerminalExpression<"f">,
			TerminalExpression<"g">,
			TerminalExpression<"h">,
			TerminalExpression<"i">,
			TerminalExpression<"j">,
			TerminalExpression<"k">,
			TerminalExpression<"l">,
			TerminalExpression<"m">,
			TerminalExpression<"n">,
			TerminalExpression<"o">,
			TerminalExpression<"p">,
			TerminalExpression<"q">,
			TerminalExpression<"r">,
			TerminalExpression<"s">,
			TerminalExpression<"t">,
			TerminalExpression<"u">,
			TerminalExpression<"v">,
			TerminalExpression<"w">,
			TerminalExpression<"x">,
			TerminalExpression<"y">,
			TerminalExpression<"z">,
		] = [
			new TerminalExpression("!"),
			new TerminalExpression("#"),
			new TerminalExpression("$"),
			new TerminalExpression("%"),
			new TerminalExpression("&"),
			new TerminalExpression("*"),
			new TerminalExpression("+"),
			new TerminalExpression(","),
			new TerminalExpression("-"),
			new TerminalExpression("."),
			new TerminalExpression("/"),
			new TerminalExpression("0"),
			new TerminalExpression("1"),
			new TerminalExpression("2"),
			new TerminalExpression("3"),
			new TerminalExpression("4"),
			new TerminalExpression("5"),
			new TerminalExpression("6"),
			new TerminalExpression("7"),
			new TerminalExpression("8"),
			new TerminalExpression("9"),
			new TerminalExpression(":"),
			new TerminalExpression(";"),
			new TerminalExpression("<"),
			new TerminalExpression("="),
			new TerminalExpression(">"),
			new TerminalExpression("?"),
			new TerminalExpression("@"),
			new TerminalExpression("A"),
			new TerminalExpression("B"),
			new TerminalExpression("C"),
			new TerminalExpression("D"),
			new TerminalExpression("E"),
			new TerminalExpression("F"),
			new TerminalExpression("G"),
			new TerminalExpression("H"),
			new TerminalExpression("I"),
			new TerminalExpression("J"),
			new TerminalExpression("K"),
			new TerminalExpression("L"),
			new TerminalExpression("M"),
			new TerminalExpression("N"),
			new TerminalExpression("O"),
			new TerminalExpression("P"),
			new TerminalExpression("Q"),
			new TerminalExpression("R"),
			new TerminalExpression("S"),
			new TerminalExpression("T"),
			new TerminalExpression("U"),
			new TerminalExpression("V"),
			new TerminalExpression("W"),
			new TerminalExpression("X"),
			new TerminalExpression("Y"),
			new TerminalExpression("Z"),
			new TerminalExpression("^"),
			new TerminalExpression("_"),
			new TerminalExpression("a"),
			new TerminalExpression("b"),
			new TerminalExpression("c"),
			new TerminalExpression("d"),
			new TerminalExpression("e"),
			new TerminalExpression("f"),
			new TerminalExpression("g"),
			new TerminalExpression("h"),
			new TerminalExpression("i"),
			new TerminalExpression("j"),
			new TerminalExpression("k"),
			new TerminalExpression("l"),
			new TerminalExpression("m"),
			new TerminalExpression("n"),
			new TerminalExpression("o"),
			new TerminalExpression("p"),
			new TerminalExpression("q"),
			new TerminalExpression("r"),
			new TerminalExpression("s"),
			new TerminalExpression("t"),
			new TerminalExpression("u"),
			new TerminalExpression("v"),
			new TerminalExpression("w"),
			new TerminalExpression("x"),
			new TerminalExpression("y"),
			new TerminalExpression("z"),
		];
		return rightExpressions;
	}
}
