import type {BranchConcreteSyntaxTreeNode} from "../../BranchConcreteSyntaxTreeNode.ts";
import type {FunctionHeaderUnknownStartingSegmentsConcreteSyntaxTreeNodeChildren} from "./FunctionHeaderUnknownStartingSegmentsConcreteSyntaxTreeNodeChildren.ts";
import type {functionHeaderUnknownStartingSegmentsConcreteSyntaxTreeNodeTypeName} from "./functionHeaderUnknownStartingSegmentsConcreteSyntaxTreeNodeTypeName.ts";
export type FunctionHeaderUnknownStartingSegmentsConcreteSyntaxTreeNode =
	BranchConcreteSyntaxTreeNode<
		typeof functionHeaderUnknownStartingSegmentsConcreteSyntaxTreeNodeTypeName,
		FunctionHeaderUnknownStartingSegmentsConcreteSyntaxTreeNodeChildren
	>;
