import type {BranchConcreteSyntaxTreeNode} from "../../BranchConcreteSyntaxTreeNode.ts";
import type {FunctionHeaderKnownSegmentContentConcreteSyntaxTreeNodeChildren} from "./FunctionHeaderKnownSegmentContentConcreteSyntaxTreeNodeChildren.ts";
import type {functionHeaderKnownSegmentContentConcreteSyntaxTreeNodeTypeName} from "./functionHeaderKnownSegmentContentConcreteSyntaxTreeNodeTypeName.ts";
export type FunctionHeaderKnownSegmentContentConcreteSyntaxTreeNode = BranchConcreteSyntaxTreeNode<
	typeof functionHeaderKnownSegmentContentConcreteSyntaxTreeNodeTypeName,
	FunctionHeaderKnownSegmentContentConcreteSyntaxTreeNodeChildren
>;
