import type {BlockStatementRule} from "../rule/implementations/block-statement/BlockStatementRule.ts";
import type {BlockStatementContentRule} from "../rule/implementations/block-statement-content/BlockStatementContentRule.ts";
import type {ClosingCurlyBracketCharacterRule} from "../rule/implementations/closing-curly-bracket-character/ClosingCurlyBracketCharacterRule.ts";
import type {ClosingRoundBracketCharacterRule} from "../rule/implementations/closing-round-bracket-character/ClosingRoundBracketCharacterRule.ts";
import type {ClosingSquareBracketCharacterRule} from "../rule/implementations/closing-square-bracket-character/ClosingSquareBracketCharacterRule.ts";
import type {ContentRule} from "../rule/implementations/content/ContentRule.ts";
import type {EmptyRule} from "../rule/implementations/empty/EmptyRule.ts";
import type {FunctionRule} from "../rule/implementations/function/FunctionRule.ts";
import type {FunctionBodyRule} from "../rule/implementations/function-body/FunctionBodyRule.ts";
import type {FunctionCallStatementRule} from "../rule/implementations/function-call-statement/FunctionCallStatementRule.ts";
import type {FunctionCallStatementSegmentsRule} from "../rule/implementations/function-call-statement-segments/FunctionCallStatementSegmentsRule.ts";
import type {FunctionHeaderRule} from "../rule/implementations/function-header/FunctionHeaderRule.ts";
import type {FunctionHeaderSegmentsRule} from "../rule/implementations/function-header-segments/FunctionHeaderSegmentsRule.ts";
import type {FunctionsRule} from "../rule/implementations/functions/FunctionsRule.ts";
import type {KnownFunctionCallStatementSegmentRule} from "../rule/implementations/known-function-call-statement-segment/KnownFunctionCallStatementSegmentRule.ts";
import type {KnownFunctionCallStatementSegmentContentRule} from "../rule/implementations/known-function-call-statement-segmentContent/KnownFunctionCallStatementSegmentContentRule.ts";
import type {KnownFunctionHeaderSegmentRule} from "../rule/implementations/known-function-header-segment/KnownFunctionHeaderSegmentRule.ts";
import type {KnownFunctionHeaderSegmentContentRule} from "../rule/implementations/known-function-header-segmentContent/KnownFunctionHeaderSegmentContentRule.ts";
import type {OpeningCurlyBracketCharacterRule} from "../rule/implementations/opening-curly-bracket-character/OpeningCurlyBracketCharacterRule.ts";
import type {OpeningRoundBracketCharacterRule} from "../rule/implementations/opening-round-bracket-character/OpeningRoundBracketCharacterRule.ts";
import type {OpeningSquareBracketCharacterRule} from "../rule/implementations/opening-square-bracket-character/OpeningSquareBracketCharacterRule.ts";
import type {OperatorRule} from "../rule/implementations/operator/OperatorRule.ts";
import type {OptionalBlockStatementContentRule} from "../rule/implementations/optional-block-statement-content/OptionalBlockStatementContentRule.ts";
import type {OptionalContentRule} from "../rule/implementations/optional-content/OptionalContentRule.ts";
import type {OptionalFunctionCallStatementSegmentsRule} from "../rule/implementations/optional-function-call-statement-segments/OptionalFunctionCallStatementSegmentsRule.ts";
import type {OptionalFunctionHeaderRule} from "../rule/implementations/optional-function-header/OptionalFunctionHeaderRule.ts";
import type {OptionalFunctionHeaderSegmentsRule} from "../rule/implementations/optional-function-header-segments/OptionalFunctionHeaderSegmentsRule.ts";
import type {OptionalFunctionsRule} from "../rule/implementations/optional-functions/OptionalFunctionsRule.ts";
import type {OptionalKnownFunctionCallStatementSegmentContentRule} from "../rule/implementations/optional-known-function-call-statement-segment-content/OptionalKnownFunctionCallStatementSegmentContentRule.ts";
import type {OptionalKnownFunctionHeaderSegmentContentRule} from "../rule/implementations/optional-known-function-header-segment-content/OptionalKnownFunctionHeaderSegmentContentRule.ts";
import type {OptionalSeparatedOptionalVariableNameSegmentsRule} from "../rule/implementations/optional-separated-optional-variable-name-segments/OptionalSeparatedOptionalVariableNameSegmentsRule.ts";
import type {OptionalSeparatedStatementsRule} from "../rule/implementations/optional-separated-statements/OptionalSeparatedStatementsRule.ts";
import type {OptionalStartingWithKnownFunctionCallStatementSegmentsRestRule} from "../rule/implementations/optional-starting-with-known-function-call-statement-segments-rest/OptionalStartingWithKnownFunctionCallStatementSegmentsRestRule.ts";
import type {OptionalStartingWithKnownFunctionHeaderSegmentsRestRule} from "../rule/implementations/optional-starting-with-known-function-header-segments-rest/OptionalStartingWithKnownFunctionHeaderSegmentsRestRule.ts";
import type {OptionalStartingWithUnknownFunctionCallStatementSegmentsRestRule} from "../rule/implementations/optional-starting-with-unknown-function-call-statement-segments-rest/OptionalStartingWithUnknownFunctionCallStatementSegmentsRestRule.ts";
import type {OptionalStartingWithUnknownFunctionHeaderSegmentsRestRule} from "../rule/implementations/optional-starting-with-unknown-function-header-segments-rest/OptionalStartingWithUnknownFunctionHeaderSegmentsRestRule.ts";
import type {OptionalStartingWithWordFunctionCallStatementSegmentsRestRule} from "../rule/implementations/optional-starting-with-word-function-call-statement-segments-rest/OptionalStartingWithWordFunctionCallStatementSegmentsRestRule.ts";
import type {OptionalStartingWithWordFunctionHeaderSegmentsRestRule} from "../rule/implementations/optional-starting-with-word-function-header-segments-rest/OptionalStartingWithWordFunctionHeaderSegmentsRestRule.ts";
import type {OptionalStatementsRule} from "../rule/implementations/optional-statements/OptionalStatementsRule.ts";
import type {OptionalUnknownFunctionCallStatementSegmentContentRule} from "../rule/implementations/optional-unknown-function-call-statement-segment-content/OptionalUnknownFunctionCallStatementSegmentContentRule.ts";
import type {OptionalUnknownFunctionHeaderSegmentContentRule} from "../rule/implementations/optional-unknown-function-header-segment-content/OptionalUnknownFunctionHeaderSegmentContentRule.ts";
import type {OptionalVariableNameRule} from "../rule/implementations/optional-variable-name/OptionalVariableNameRule.ts";
import type {OptionalVariableNameSegmentCharactersRule} from "../rule/implementations/optional-variable-name-segment-characters/OptionalVariableNameSegmentCharactersRule.ts";
import type {OptionalVariableNameSegmentsRule} from "../rule/implementations/optional-variable-name-segments/OptionalVariableNameSegmentsRule.ts";
import type {OptionalWhitespaceRule} from "../rule/implementations/optional-whitespace/OptionalWhitespaceRule.ts";
import type {OptionalWhitespaceCharactersRule} from "../rule/implementations/optional-whitespace-characters/OptionalWhitespaceCharactersRule.ts";
import type {OptionalWordCharactersRule} from "../rule/implementations/optional-word-characters/OptionalWordCharactersRule.ts";
import type {OrOperatorRule} from "../rule/implementations/or-operator/OrOperatorRule.ts";
import type {PaddedOptionalFunctionsRule} from "../rule/implementations/padded-optional-functions/PaddedOptionalFunctionsRule.ts";
import type {PaddedOptionalStatementsRule} from "../rule/implementations/padded-optional-statements/PaddedOptionalStatementsRule.ts";
import type {PaddedOptionalVariableNameRule} from "../rule/implementations/padded-optional-variable-name/PaddedOptionalVariableNameRule.ts";
import type {SeparatedOptionalFunctionCallStatementSegmentsRule} from "../rule/implementations/separated-optional-function-call-statement-segments/SeparatedOptionalFunctionCallStatementSegmentsRule.ts";
import type {SeparatedOptionalFunctionHeaderSegmentsRule} from "../rule/implementations/separated-optional-function-header-segments/SeparatedOptionalFunctionHeaderSegmentsRule.ts";
import type {SeparatedOptionalVariableNameSegmentsRule} from "../rule/implementations/separated-optional-variable-name-segments/SeparatedOptionalVariableNameSegmentsRule.ts";
import type {SeparatedStatementsRule} from "../rule/implementations/separated-statements/SeparatedStatementsRule.ts";
import type {StartingWithKnownFunctionCallStatementSegmentsRule} from "../rule/implementations/starting-with-known-function-call-statement-segments/StartingWithKnownFunctionCallStatementSegmentsRule.ts";
import type {StartingWithKnownFunctionCallStatementSegmentsRestRule} from "../rule/implementations/starting-with-known-function-call-statement-segments-rest/StartingWithKnownFunctionCallStatementSegmentsRestRule.ts";
import type {StartingWithKnownFunctionHeaderSegmentsRule} from "../rule/implementations/starting-with-known-function-header-segments/StartingWithKnownFunctionHeaderSegmentsRule.ts";
import type {StartingWithKnownFunctionHeaderSegmentsRestRule} from "../rule/implementations/starting-with-known-function-header-segments-rest/StartingWithKnownFunctionHeaderSegmentsRestRule.ts";
import type {StartingWithUnknownFunctionCallStatementSegmentsRule} from "../rule/implementations/starting-with-unknown-function-call-statement-segments/StartingWithUnknownFunctionCallStatementSegmentsRule.ts";
import type {StartingWithUnknownFunctionCallStatementSegmentsRestRule} from "../rule/implementations/starting-with-unknown-function-call-statement-segments-rest/StartingWithUnknownFunctionCallStatementSegmentsRestRule.ts";
import type {StartingWithUnknownFunctionHeaderSegmentsRule} from "../rule/implementations/starting-with-unknown-function-header-segments/StartingWithUnknownFunctionHeaderSegmentsRule.ts";
import type {StartingWithUnknownFunctionHeaderSegmentsRestRule} from "../rule/implementations/starting-with-unknown-function-header-segments-rest/StartingWithUnknownFunctionHeaderSegmentsRestRule.ts";
import type {StartingWithWordFunctionCallStatementSegmentsRule} from "../rule/implementations/starting-with-word-function-call-statement-segments/StartingWithWordFunctionCallStatementSegmentsRule.ts";
import type {StartingWithWordFunctionCallStatementSegmentsRestRule} from "../rule/implementations/starting-with-word-function-call-statement-segments-rest/StartingWithWordFunctionCallStatementSegmentsRestRule.ts";
import type {StartingWithWordFunctionHeaderSegmentsRule} from "../rule/implementations/starting-with-word-function-header-segments/StartingWithWordFunctionHeaderSegmentsRule.ts";
import type {StartingWithWordFunctionHeaderSegmentsRestRule} from "../rule/implementations/starting-with-word-function-header-segments-rest/StartingWithWordFunctionHeaderSegmentsRestRule.ts";
import type {StatementRule} from "../rule/implementations/statement/StatementRule.ts";
import type {StatementsRule} from "../rule/implementations/statements/StatementsRule.ts";
import type {ThenOperatorRule} from "../rule/implementations/then-operator/ThenOperatorRule.ts";
import type {UnknownFunctionCallStatementSegmentRule} from "../rule/implementations/unknown-function-call-statement-segment/UnknownFunctionCallStatementSegmentRule.ts";
import type {UnknownFunctionCallStatementSegmentContentRule} from "../rule/implementations/unknown-function-call-statement-segment-content/UnknownFunctionCallStatementSegmentContentRule.ts";
import type {UnknownFunctionHeaderSegmentRule} from "../rule/implementations/unknown-function-header-segment/UnknownFunctionHeaderSegmentRule.ts";
import type {UnknownFunctionHeaderSegmentContentRule} from "../rule/implementations/unknown-function-header-segment-content/UnknownFunctionHeaderSegmentContentRule.ts";
import type {VariableNameRule} from "../rule/implementations/variable-name/VariableNameRule.ts";
import type {VariableNameSegmentRule} from "../rule/implementations/variable-name-segment/VariableNameSegmentRule.ts";
import type {VariableNameSegmentCharacterRule} from "../rule/implementations/variable-name-segment-character/VariableNameSegmentCharacterRule.ts";
import type {VariableNameSegmentCharactersRule} from "../rule/implementations/variable-name-segment-characters/VariableNameSegmentCharactersRule.ts";
import type {VariableNameSegmentsRule} from "../rule/implementations/variable-name-segments/VariableNameSegmentsRule.ts";
import type {WhitespaceRule} from "../rule/implementations/whitespace/WhitespaceRule.ts";
import type {WhitespaceCharacterRule} from "../rule/implementations/whitespace-character/WhitespaceCharacterRule.ts";
import type {WhitespaceCharactersRule} from "../rule/implementations/whitespace-characters/WhitespaceCharactersRule.ts";
import type {WordRule} from "../rule/implementations/word/WordRule.ts";
import type {WordCharacterRule} from "../rule/implementations/word-character/WordCharacterRule.ts";
import type {WordCharactersRule} from "../rule/implementations/word-characters/WordCharactersRule.ts";
import type {WordFunctionCallStatementSegmentRule} from "../rule/implementations/word-function-call-statement-segment/WordFunctionCallStatementSegmentRule.ts";
import type {WordFunctionHeaderSegmentRule} from "../rule/implementations/word-function-header-segment/WordFunctionHeaderSegmentRule.ts";
export type RuleById = {
	readonly BlockStatement: BlockStatementRule;
	readonly BlockStatementContent: BlockStatementContentRule;
	readonly ClosingCurlyBracketCharacter: ClosingCurlyBracketCharacterRule;
	readonly ClosingRoundBracketCharacter: ClosingRoundBracketCharacterRule;
	readonly ClosingSquareBracketCharacter: ClosingSquareBracketCharacterRule;
	readonly Content: ContentRule;
	readonly Empty: EmptyRule;
	readonly Function: FunctionRule;
	readonly FunctionBody: FunctionBodyRule;
	readonly FunctionCallStatement: FunctionCallStatementRule;
	readonly FunctionCallStatementSegments: FunctionCallStatementSegmentsRule;
	readonly FunctionHeader: FunctionHeaderRule;
	readonly FunctionHeaderSegments: FunctionHeaderSegmentsRule;
	readonly Functions: FunctionsRule;
	readonly KnownFunctionCallStatementSegment: KnownFunctionCallStatementSegmentRule;
	readonly KnownFunctionCallStatementSegmentContent: KnownFunctionCallStatementSegmentContentRule;
	readonly KnownFunctionHeaderSegment: KnownFunctionHeaderSegmentRule;
	readonly KnownFunctionHeaderSegmentContent: KnownFunctionHeaderSegmentContentRule;
	readonly OpeningCurlyBracketCharacter: OpeningCurlyBracketCharacterRule;
	readonly OpeningRoundBracketCharacter: OpeningRoundBracketCharacterRule;
	readonly OpeningSquareBracketCharacter: OpeningSquareBracketCharacterRule;
	readonly Operator: OperatorRule;
	readonly OptionalBlockStatementContent: OptionalBlockStatementContentRule;
	readonly OptionalContent: OptionalContentRule;
	readonly OptionalFunctionCallStatementSegments: OptionalFunctionCallStatementSegmentsRule;
	readonly OptionalFunctionHeader: OptionalFunctionHeaderRule;
	readonly OptionalFunctionHeaderSegments: OptionalFunctionHeaderSegmentsRule;
	readonly OptionalFunctions: OptionalFunctionsRule;
	readonly OptionalKnownFunctionCallStatementSegmentContent: OptionalKnownFunctionCallStatementSegmentContentRule;
	readonly OptionalKnownFunctionHeaderSegmentContent: OptionalKnownFunctionHeaderSegmentContentRule;
	readonly OptionalSeparatedOptionalVariableNameSegments: OptionalSeparatedOptionalVariableNameSegmentsRule;
	readonly OptionalSeparatedStatements: OptionalSeparatedStatementsRule;
	readonly OptionalStartingWithKnownFunctionCallStatementSegmentsRest: OptionalStartingWithKnownFunctionCallStatementSegmentsRestRule;
	readonly OptionalStartingWithKnownFunctionHeaderSegmentsRest: OptionalStartingWithKnownFunctionHeaderSegmentsRestRule;
	readonly OptionalStartingWithUnknownFunctionCallStatementSegmentsRest: OptionalStartingWithUnknownFunctionCallStatementSegmentsRestRule;
	readonly OptionalStartingWithUnknownFunctionHeaderSegmentsRest: OptionalStartingWithUnknownFunctionHeaderSegmentsRestRule;
	readonly OptionalStartingWithWordFunctionCallStatementSegmentsRest: OptionalStartingWithWordFunctionCallStatementSegmentsRestRule;
	readonly OptionalStartingWithWordFunctionHeaderSegmentsRest: OptionalStartingWithWordFunctionHeaderSegmentsRestRule;
	readonly OptionalStatements: OptionalStatementsRule;
	readonly OptionalUnknownFunctionCallStatementSegmentContent: OptionalUnknownFunctionCallStatementSegmentContentRule;
	readonly OptionalUnknownFunctionHeaderSegmentContent: OptionalUnknownFunctionHeaderSegmentContentRule;
	readonly OptionalVariableName: OptionalVariableNameRule;
	readonly OptionalVariableNameSegmentCharacters: OptionalVariableNameSegmentCharactersRule;
	readonly OptionalVariableNameSegments: OptionalVariableNameSegmentsRule;
	readonly OptionalWhitespace: OptionalWhitespaceRule;
	readonly OptionalWhitespaceCharacters: OptionalWhitespaceCharactersRule;
	readonly OptionalWordCharacters: OptionalWordCharactersRule;
	readonly OrOperator: OrOperatorRule;
	readonly PaddedOptionalFunctions: PaddedOptionalFunctionsRule;
	readonly PaddedOptionalStatements: PaddedOptionalStatementsRule;
	readonly PaddedOptionalVariableName: PaddedOptionalVariableNameRule;
	readonly SeparatedOptionalFunctionCallStatementSegments: SeparatedOptionalFunctionCallStatementSegmentsRule;
	readonly SeparatedOptionalFunctionHeaderSegments: SeparatedOptionalFunctionHeaderSegmentsRule;
	readonly SeparatedOptionalVariableNameSegments: SeparatedOptionalVariableNameSegmentsRule;
	readonly SeparatedStatements: SeparatedStatementsRule;
	readonly StartingWithKnownFunctionCallStatementSegments: StartingWithKnownFunctionCallStatementSegmentsRule;
	readonly StartingWithKnownFunctionCallStatementSegmentsRest: StartingWithKnownFunctionCallStatementSegmentsRestRule;
	readonly StartingWithKnownFunctionHeaderSegments: StartingWithKnownFunctionHeaderSegmentsRule;
	readonly StartingWithKnownFunctionHeaderSegmentsRest: StartingWithKnownFunctionHeaderSegmentsRestRule;
	readonly StartingWithUnknownFunctionCallStatementSegments: StartingWithUnknownFunctionCallStatementSegmentsRule;
	readonly StartingWithUnknownFunctionCallStatementSegmentsRest: StartingWithUnknownFunctionCallStatementSegmentsRestRule;
	readonly StartingWithUnknownFunctionHeaderSegments: StartingWithUnknownFunctionHeaderSegmentsRule;
	readonly StartingWithUnknownFunctionHeaderSegmentsRest: StartingWithUnknownFunctionHeaderSegmentsRestRule;
	readonly StartingWithWordFunctionCallStatementSegments: StartingWithWordFunctionCallStatementSegmentsRule;
	readonly StartingWithWordFunctionCallStatementSegmentsRest: StartingWithWordFunctionCallStatementSegmentsRestRule;
	readonly StartingWithWordFunctionHeaderSegments: StartingWithWordFunctionHeaderSegmentsRule;
	readonly StartingWithWordFunctionHeaderSegmentsRest: StartingWithWordFunctionHeaderSegmentsRestRule;
	readonly Statement: StatementRule;
	readonly Statements: StatementsRule;
	readonly ThenOperator: ThenOperatorRule;
	readonly UnknownFunctionCallStatementSegment: UnknownFunctionCallStatementSegmentRule;
	readonly UnknownFunctionCallStatementSegmentContent: UnknownFunctionCallStatementSegmentContentRule;
	readonly UnknownFunctionHeaderSegment: UnknownFunctionHeaderSegmentRule;
	readonly UnknownFunctionHeaderSegmentContent: UnknownFunctionHeaderSegmentContentRule;
	readonly VariableName: VariableNameRule;
	readonly VariableNameSegment: VariableNameSegmentRule;
	readonly VariableNameSegmentCharacter: VariableNameSegmentCharacterRule;
	readonly VariableNameSegmentCharacters: VariableNameSegmentCharactersRule;
	readonly VariableNameSegments: VariableNameSegmentsRule;
	readonly Whitespace: WhitespaceRule;
	readonly WhitespaceCharacter: WhitespaceCharacterRule;
	readonly WhitespaceCharacters: WhitespaceCharactersRule;
	readonly Word: WordRule;
	readonly WordCharacter: WordCharacterRule;
	readonly WordCharacters: WordCharactersRule;
	readonly WordFunctionCallStatementSegment: WordFunctionCallStatementSegmentRule;
	readonly WordFunctionHeaderSegment: WordFunctionHeaderSegmentRule;
};
