import type {EmptyConcreteSyntaxTreeNode} from "../concrete-syntax-tree-node/implementations/empty/EmptyConcreteSyntaxTreeNode.ts";
import type {BlockRule} from "../rule/implementations/block/BlockRule.ts";
import type {BlockContentRule} from "../rule/implementations/block-content/BlockContentRule.ts";
import type {BlockStatementRule} from "../rule/implementations/block-statement/BlockStatementRule.ts";
import type {ClosingCurlyBracketCharacterRule} from "../rule/implementations/closing-curly-bracket-character/ClosingCurlyBracketCharacterRule.ts";
import type {ClosingRoundBracketCharacterRule} from "../rule/implementations/closing-round-bracket-character/ClosingRoundBracketCharacterRule.ts";
import type {ClosingSquareBracketCharacterRule} from "../rule/implementations/closing-square-bracket-character/ClosingSquareBracketCharacterRule.ts";
import type {ContentRule} from "../rule/implementations/content/ContentRule.ts";
import type {EmptyRule} from "../rule/implementations/empty/EmptyRule.ts";
import type {FunctionRule} from "../rule/implementations/function/FunctionRule.ts";
import type {FunctionBodyRule} from "../rule/implementations/function-body/FunctionBodyRule.ts";
import type {FunctionCallRule} from "../rule/implementations/function-call/FunctionCallRule.ts";
import type {FunctionCallSegmentsRule} from "../rule/implementations/function-call-segments/FunctionCallSegmentsRule.ts";
import type {FunctionCallStatementRule} from "../rule/implementations/function-call-statement/FunctionCallStatementRule.ts";
import type {FunctionHeaderRule} from "../rule/implementations/function-header/FunctionHeaderRule.ts";
import type {FunctionHeaderSegmentsRule} from "../rule/implementations/function-header-segments/FunctionHeaderSegmentsRule.ts";
import type {FunctionsRule} from "../rule/implementations/functions/FunctionsRule.ts";
import type {KnownFunctionCallSegmentRule} from "../rule/implementations/known-function-call-segment/KnownFunctionCallSegmentRule.ts";
import type {KnownFunctionCallSegmentContentRule} from "../rule/implementations/known-function-call-segmentContent/KnownFunctionCallSegmentContentRule.ts";
import type {KnownFunctionHeaderSegmentRule} from "../rule/implementations/known-function-header-segment/KnownFunctionHeaderSegmentRule.ts";
import type {KnownFunctionHeaderSegmentContentRule} from "../rule/implementations/known-function-header-segmentContent/KnownFunctionHeaderSegmentContentRule.ts";
import type {OpeningCurlyBracketCharacterRule} from "../rule/implementations/opening-curly-bracket-character/OpeningCurlyBracketCharacterRule.ts";
import type {OpeningRoundBracketCharacterRule} from "../rule/implementations/opening-round-bracket-character/OpeningRoundBracketCharacterRule.ts";
import type {OpeningSquareBracketCharacterRule} from "../rule/implementations/opening-square-bracket-character/OpeningSquareBracketCharacterRule.ts";
import type {OperatorRule} from "../rule/implementations/operator/OperatorRule.ts";
import type {OptionalBlockContentRule} from "../rule/implementations/optional-block-content/OptionalBlockContentRule.ts";
import type {OptionalContentRule} from "../rule/implementations/optional-content/OptionalContentRule.ts";
import type {OptionalFunctionCallSegmentsRule} from "../rule/implementations/optional-function-call-segments/OptionalFunctionCallSegmentsRule.ts";
import type {OptionalFunctionHeaderRule} from "../rule/implementations/optional-function-header/OptionalFunctionHeaderRule.ts";
import type {OptionalFunctionHeaderSegmentsRule} from "../rule/implementations/optional-function-header-segments/OptionalFunctionHeaderSegmentsRule.ts";
import type {OptionalFunctionsRule} from "../rule/implementations/optional-functions/OptionalFunctionsRule.ts";
import type {OptionalKnownFunctionCallSegmentContentRule} from "../rule/implementations/optional-known-function-call-segment-content/OptionalKnownFunctionCallSegmentContentRule.ts";
import type {OptionalKnownFunctionHeaderSegmentContentRule} from "../rule/implementations/optional-known-function-header-segment-content/OptionalKnownFunctionHeaderSegmentContentRule.ts";
import type {OptionalPaddedVariableNameRule} from "../rule/implementations/optional-padded-variable-name/OptionalPaddedVariableNameRule.ts";
import type {OptionalSeparatedStatementsRule} from "../rule/implementations/optional-separated-statements/OptionalSeparatedStatementsRule.ts";
import type {OptionalStartingWithKnownFunctionCallSegmentsRestRule} from "../rule/implementations/optional-starting-with-known-function-call-segments-rest/OptionalStartingWithKnownFunctionCallSegmentsRestRule.ts";
import type {OptionalStartingWithKnownFunctionHeaderSegmentsRestRule} from "../rule/implementations/optional-starting-with-known-function-header-segments-rest/OptionalStartingWithKnownFunctionHeaderSegmentsRestRule.ts";
import type {OptionalStartingWithUnknownFunctionCallSegmentsRestRule} from "../rule/implementations/optional-starting-with-unknown-function-call-segments-rest/OptionalStartingWithUnknownFunctionCallSegmentsRestRule.ts";
import type {OptionalStartingWithUnknownFunctionHeaderSegmentsRestRule} from "../rule/implementations/optional-starting-with-unknown-function-header-segments-rest/OptionalStartingWithUnknownFunctionHeaderSegmentsRestRule.ts";
import type {OptionalStartingWithWordFunctionCallSegmentsRestRule} from "../rule/implementations/optional-starting-with-word-function-call-segments-rest/OptionalStartingWithWordFunctionCallSegmentsRestRule.ts";
import type {OptionalStartingWithWordFunctionHeaderSegmentsRestRule} from "../rule/implementations/optional-starting-with-word-function-header-segments-rest/OptionalStartingWithWordFunctionHeaderSegmentsRestRule.ts";
import type {OptionalStatementsRule} from "../rule/implementations/optional-statements/OptionalStatementsRule.ts";
import type {OptionalUnknownFunctionCallSegmentContentRule} from "../rule/implementations/optional-unknown-function-call-segment-content/OptionalUnknownFunctionCallSegmentContentRule.ts";
import type {OptionalUnknownFunctionHeaderSegmentContentRule} from "../rule/implementations/optional-unknown-function-header-segment-content/OptionalUnknownFunctionHeaderSegmentContentRule.ts";
import type {OptionalVariableNameCharactersRule} from "../rule/implementations/optional-variable-name-characters/OptionalVariableNameCharactersRule.ts";
import type {OptionalWhitespaceRule} from "../rule/implementations/optional-whitespace/OptionalWhitespaceRule.ts";
import type {OptionalWhitespaceCharactersRule} from "../rule/implementations/optional-whitespace-characters/OptionalWhitespaceCharactersRule.ts";
import type {OptionalWordCharactersRule} from "../rule/implementations/optional-word-characters/OptionalWordCharactersRule.ts";
import type {OrOperatorRule} from "../rule/implementations/or-operator/OrOperatorRule.ts";
import type {PaddedOptionalFunctionsRule} from "../rule/implementations/padded-optional-functions/PaddedOptionalFunctionsRule.ts";
import type {PaddedOptionalPaddedVariableNameRule} from "../rule/implementations/padded-optional-padded-variable-name/PaddedOptionalPaddedVariableNameRule.ts";
import type {PaddedOptionalStatementsRule} from "../rule/implementations/padded-optional-statements/PaddedOptionalStatementsRule.ts";
import type {PaddedVariableNameRule} from "../rule/implementations/padded-variable-name/PaddedVariableNameRule.ts";
import type {SeparatedOptionalFunctionCallSegmentsRule} from "../rule/implementations/separated-optional-function-call-segments/SeparatedOptionalFunctionCallSegmentsRule.ts";
import type {SeparatedOptionalFunctionHeaderSegmentsRule} from "../rule/implementations/separated-optional-function-header-segments/SeparatedOptionalFunctionHeaderSegmentsRule.ts";
import type {SeparatedStatementsRule} from "../rule/implementations/separated-statements/SeparatedStatementsRule.ts";
import type {StartingWithKnownFunctionCallSegmentsRule} from "../rule/implementations/starting-with-known-function-call-segments/StartingWithKnownFunctionCallSegmentsRule.ts";
import type {StartingWithKnownFunctionCallSegmentsRestRule} from "../rule/implementations/starting-with-known-function-call-segments-rest/StartingWithKnownFunctionCallSegmentsRestRule.ts";
import type {StartingWithKnownFunctionHeaderSegmentsRule} from "../rule/implementations/starting-with-known-function-header-segments/StartingWithKnownFunctionHeaderSegmentsRule.ts";
import type {StartingWithKnownFunctionHeaderSegmentsRestRule} from "../rule/implementations/starting-with-known-function-header-segments-rest/StartingWithKnownFunctionHeaderSegmentsRestRule.ts";
import type {StartingWithUnknownFunctionCallSegmentsRule} from "../rule/implementations/starting-with-unknown-function-call-segments/StartingWithUnknownFunctionCallSegmentsRule.ts";
import type {StartingWithUnknownFunctionCallSegmentsRestRule} from "../rule/implementations/starting-with-unknown-function-call-segments-rest/StartingWithUnknownFunctionCallSegmentsRestRule.ts";
import type {StartingWithUnknownFunctionHeaderSegmentsRule} from "../rule/implementations/starting-with-unknown-function-header-segments/StartingWithUnknownFunctionHeaderSegmentsRule.ts";
import type {StartingWithUnknownFunctionHeaderSegmentsRestRule} from "../rule/implementations/starting-with-unknown-function-header-segments-rest/StartingWithUnknownFunctionHeaderSegmentsRestRule.ts";
import type {StartingWithWordFunctionCallSegmentsRule} from "../rule/implementations/starting-with-word-function-call-segments/StartingWithWordFunctionCallSegmentsRule.ts";
import type {StartingWithWordFunctionCallSegmentsRestRule} from "../rule/implementations/starting-with-word-function-call-segments-rest/StartingWithWordFunctionCallSegmentsRestRule.ts";
import type {StartingWithWordFunctionHeaderSegmentsRule} from "../rule/implementations/starting-with-word-function-header-segments/StartingWithWordFunctionHeaderSegmentsRule.ts";
import type {StartingWithWordFunctionHeaderSegmentsRestRule} from "../rule/implementations/starting-with-word-function-header-segments-rest/StartingWithWordFunctionHeaderSegmentsRestRule.ts";
import type {StatementRule} from "../rule/implementations/statement/StatementRule.ts";
import type {StatementsRule} from "../rule/implementations/statements/StatementsRule.ts";
import type {ThenOperatorRule} from "../rule/implementations/then-operator-character/ThenOperatorRule.ts";
import type {UnknownFunctionCallSegmentRule} from "../rule/implementations/unknown-function-call-segment/UnknownFunctionCallSegmentRule.ts";
import type {UnknownFunctionCallSegmentContentRule} from "../rule/implementations/unknown-function-call-segment-content/UnknownFunctionCallSegmentContentRule.ts";
import type {UnknownFunctionHeaderSegmentRule} from "../rule/implementations/unknown-function-header-segment/UnknownFunctionHeaderSegmentRule.ts";
import type {UnknownFunctionHeaderSegmentContentRule} from "../rule/implementations/unknown-function-header-segment-content/UnknownFunctionHeaderSegmentContentRule.ts";
import type {VariableNameRule} from "../rule/implementations/variable-name/VariableNameRule.ts";
import type {VariableNameCharacterRule} from "../rule/implementations/variable-name-character/VariableNameCharacterRule.ts";
import type {VariableNameCharactersRule} from "../rule/implementations/variable-name-characters/VariableNameCharactersRule.ts";
import type {WhitespaceRule} from "../rule/implementations/whitespace/WhitespaceRule.ts";
import type {WhitespaceCharacterRule} from "../rule/implementations/whitespace-character/WhitespaceCharacterRule.ts";
import type {WhitespaceCharactersRule} from "../rule/implementations/whitespace-characters/WhitespaceCharactersRule.ts";
import type {WordRule} from "../rule/implementations/word/WordRule.ts";
import type {WordCharacterRule} from "../rule/implementations/word-character/WordCharacterRule.ts";
import type {WordCharactersRule} from "../rule/implementations/word-characters/WordCharactersRule.ts";
import type {WordFunctionCallSegmentRule} from "../rule/implementations/word-function-call-segment/WordFunctionCallSegmentRule.ts";
import type {WordFunctionHeaderSegmentRule} from "../rule/implementations/word-function-header-segment/WordFunctionHeaderSegmentRule.ts";
export type RuleById = {
	readonly Block: BlockRule;
	readonly BlockContent: BlockContentRule;
	readonly BlockStatement: BlockStatementRule;
	readonly ClosingCurlyBracketCharacter: ClosingCurlyBracketCharacterRule;
	readonly ClosingRoundBracketCharacter: ClosingRoundBracketCharacterRule;
	readonly ClosingSquareBracketCharacter: ClosingSquareBracketCharacterRule;
	readonly Content: ContentRule;
	readonly Empty: EmptyRule;
	readonly Function: FunctionRule;
	readonly FunctionBody: FunctionBodyRule;
	readonly FunctionCall: FunctionCallRule;
	readonly FunctionCallSegments: FunctionCallSegmentsRule;
	readonly FunctionCallStatement: FunctionCallStatementRule;
	readonly FunctionHeader: FunctionHeaderRule;
	readonly FunctionHeaderSegments: FunctionHeaderSegmentsRule;
	readonly Functions: FunctionsRule;
	readonly KnownFunctionCallSegment: KnownFunctionCallSegmentRule;
	readonly KnownFunctionCallSegmentContent: KnownFunctionCallSegmentContentRule;
	readonly KnownFunctionHeaderSegment: KnownFunctionHeaderSegmentRule;
	readonly KnownFunctionHeaderSegmentContent: KnownFunctionHeaderSegmentContentRule;
	readonly OpeningCurlyBracketCharacter: OpeningCurlyBracketCharacterRule;
	readonly OpeningRoundBracketCharacter: OpeningRoundBracketCharacterRule;
	readonly OpeningSquareBracketCharacter: OpeningSquareBracketCharacterRule;
	readonly Operator: OperatorRule;
	readonly OptionalBlockContent: OptionalBlockContentRule;
	readonly OptionalContent: OptionalContentRule;
	readonly OptionalFunctionCallSegments: OptionalFunctionCallSegmentsRule;
	readonly OptionalFunctionHeader: OptionalFunctionHeaderRule;
	readonly OptionalFunctionHeaderSegments: OptionalFunctionHeaderSegmentsRule;
	readonly OptionalFunctions: OptionalFunctionsRule;
	readonly OptionalKnownFunctionCallSegmentContent: OptionalKnownFunctionCallSegmentContentRule;
	readonly OptionalKnownFunctionHeaderSegmentContent: OptionalKnownFunctionHeaderSegmentContentRule;
	readonly OptionalPaddedVariableName: OptionalPaddedVariableNameRule;
	readonly OptionalSeparatedStatements: OptionalSeparatedStatementsRule;
	readonly OptionalStartingWithKnownFunctionCallSegmentsRest: OptionalStartingWithKnownFunctionCallSegmentsRestRule;
	readonly OptionalStartingWithKnownFunctionHeaderSegmentsRest: OptionalStartingWithKnownFunctionHeaderSegmentsRestRule;
	readonly OptionalStartingWithUnknownFunctionCallSegmentsRest: OptionalStartingWithUnknownFunctionCallSegmentsRestRule;
	readonly OptionalStartingWithUnknownFunctionHeaderSegmentsRest: OptionalStartingWithUnknownFunctionHeaderSegmentsRestRule;
	readonly OptionalStartingWithWordFunctionCallSegmentsRest: OptionalStartingWithWordFunctionCallSegmentsRestRule;
	readonly OptionalStartingWithWordFunctionHeaderSegmentsRest: OptionalStartingWithWordFunctionHeaderSegmentsRestRule;
	readonly OptionalStatements: OptionalStatementsRule;
	readonly OptionalUnknownFunctionCallSegmentContent: OptionalUnknownFunctionCallSegmentContentRule;
	readonly OptionalUnknownFunctionHeaderSegmentContent: OptionalUnknownFunctionHeaderSegmentContentRule;
	readonly OptionalVariableNameCharacters: OptionalVariableNameCharactersRule;
	readonly OptionalWhitespace: OptionalWhitespaceRule;
	readonly OptionalWhitespaceCharacters: OptionalWhitespaceCharactersRule;
	readonly OptionalWordCharacters: OptionalWordCharactersRule;
	readonly OrOperator: OrOperatorRule;
	readonly PaddedOptionalFunctions: PaddedOptionalFunctionsRule;
	readonly PaddedOptionalPaddedVariableName: PaddedOptionalPaddedVariableNameRule;
	readonly PaddedOptionalStatements: PaddedOptionalStatementsRule;
	readonly PaddedVariableName: PaddedVariableNameRule;
	readonly SeparatedOptionalFunctionCallSegments: SeparatedOptionalFunctionCallSegmentsRule;
	readonly SeparatedOptionalFunctionHeaderSegments: SeparatedOptionalFunctionHeaderSegmentsRule;
	readonly SeparatedStatements: SeparatedStatementsRule;
	readonly StartingWithKnownFunctionCallSegments: StartingWithKnownFunctionCallSegmentsRule;
	readonly StartingWithKnownFunctionCallSegmentsRest: StartingWithKnownFunctionCallSegmentsRestRule;
	readonly StartingWithKnownFunctionHeaderSegments: StartingWithKnownFunctionHeaderSegmentsRule;
	readonly StartingWithKnownFunctionHeaderSegmentsRest: StartingWithKnownFunctionHeaderSegmentsRestRule;
	readonly StartingWithUnknownFunctionCallSegments: StartingWithUnknownFunctionCallSegmentsRule;
	readonly StartingWithUnknownFunctionCallSegmentsRest: StartingWithUnknownFunctionCallSegmentsRestRule;
	readonly StartingWithUnknownFunctionHeaderSegments: StartingWithUnknownFunctionHeaderSegmentsRule;
	readonly StartingWithUnknownFunctionHeaderSegmentsRest: StartingWithUnknownFunctionHeaderSegmentsRestRule;
	readonly StartingWithWordFunctionCallSegments: StartingWithWordFunctionCallSegmentsRule;
	readonly StartingWithWordFunctionCallSegmentsRest: StartingWithWordFunctionCallSegmentsRestRule;
	readonly StartingWithWordFunctionHeaderSegments: StartingWithWordFunctionHeaderSegmentsRule;
	readonly StartingWithWordFunctionHeaderSegmentsRest: StartingWithWordFunctionHeaderSegmentsRestRule;
	readonly Statement: StatementRule;
	readonly Statements: StatementsRule;
	readonly ThenOperator: ThenOperatorRule;
	readonly UnknownFunctionCallSegment: UnknownFunctionCallSegmentRule;
	readonly UnknownFunctionCallSegmentContent: UnknownFunctionCallSegmentContentRule;
	readonly UnknownFunctionHeaderSegment: UnknownFunctionHeaderSegmentRule;
	readonly UnknownFunctionHeaderSegmentContent: UnknownFunctionHeaderSegmentContentRule;
	readonly VariableName: VariableNameRule;
	readonly VariableNameCharacter: VariableNameCharacterRule;
	readonly VariableNameCharacters: VariableNameCharactersRule;
	readonly Whitespace: WhitespaceRule;
	readonly WhitespaceCharacter: WhitespaceCharacterRule;
	readonly WhitespaceCharacters: WhitespaceCharactersRule;
	readonly Word: WordRule;
	readonly WordCharacter: WordCharacterRule;
	readonly WordCharacters: WordCharactersRule;
	readonly WordFunctionCallSegment: WordFunctionCallSegmentRule;
	readonly WordFunctionHeaderSegment: WordFunctionHeaderSegmentRule;
};
