import type {BranchConcreteSyntaxTreeNode} from "../../../BranchConcreteSyntaxTreeNode.ts";
import type {FunctionHeaderKnownSegmentContentConcreteSyntaxTreeNodeDataChildren} from "./FunctionHeaderKnownSegmentContentConcreteSyntaxTreeNodeDataChildren.ts";
import type {functionHeaderKnownSegmentContentConcreteSyntaxTreeNodeKindName} from "./functionHeaderKnownSegmentContentConcreteSyntaxTreeNodeKindName.ts";
export type FunctionHeaderKnownSegmentContentConcreteSyntaxTreeNode =
	BranchConcreteSyntaxTreeNode<
		typeof functionHeaderKnownSegmentContentConcreteSyntaxTreeNodeKindName,
		FunctionHeaderKnownSegmentContentConcreteSyntaxTreeNodeDataChildren
	>;
