import type {BranchConcreteSyntaxTreeNode} from "../../../BranchConcreteSyntaxTreeNode.ts";
import type {FunctionCallSegmentsSeparatedRestSegmentsConcreteSyntaxTreeNodeChildren} from "./FunctionCallSegmentsSeparatedRestSegmentsConcreteSyntaxTreeNodeChildren.ts";
import type {functionCallSegmentsSeparatedRestSegmentsConcreteSyntaxTreeNodeKindName} from "./functionCallSegmentsSeparatedRestSegmentsConcreteSyntaxTreeNodeKindName.ts";
export type FunctionCallSegmentsSeparatedRestSegmentsConcreteSyntaxTreeNode =
	BranchConcreteSyntaxTreeNode<
		typeof functionCallSegmentsSeparatedRestSegmentsConcreteSyntaxTreeNodeKindName,
		FunctionCallSegmentsSeparatedRestSegmentsConcreteSyntaxTreeNodeChildren
	>;
