import type {BranchConcreteSyntaxTreeNode} from "../../../BranchConcreteSyntaxTreeNode.ts";
import type {FunctionHeaderUnknownStartingSegmentsConcreteSyntaxTreeNodeDataChildren} from "./FunctionHeaderUnknownStartingSegmentsConcreteSyntaxTreeNodeDataChildren.ts";
import type {functionHeaderUnknownStartingSegmentsConcreteSyntaxTreeNodeKindName} from "./functionHeaderUnknownStartingSegmentsConcreteSyntaxTreeNodeKindName.ts";
export type FunctionHeaderUnknownStartingSegmentsConcreteSyntaxTreeNode =
	BranchConcreteSyntaxTreeNode<
		typeof functionHeaderUnknownStartingSegmentsConcreteSyntaxTreeNodeKindName,
		FunctionHeaderUnknownStartingSegmentsConcreteSyntaxTreeNodeDataChildren
	>;
