import type {BranchConcreteSyntaxTreeNode} from "../../branch/BranchConcreteSyntaxTreeNode.ts";
import type {FunctionHeaderUnknownStartingSegmentsConcreteSyntaxTreeNodeDataChildren} from "./data-children/FunctionHeaderUnknownStartingSegmentsConcreteSyntaxTreeNodeDataChildren.ts";
import type {functionHeaderUnknownStartingSegmentsConcreteSyntaxTreeNodeKindName} from "./kind-name/functionHeaderUnknownStartingSegmentsConcreteSyntaxTreeNodeKindName.ts";
export type FunctionHeaderUnknownStartingSegmentsConcreteSyntaxTreeNode =
	BranchConcreteSyntaxTreeNode<
		typeof functionHeaderUnknownStartingSegmentsConcreteSyntaxTreeNodeKindName,
		FunctionHeaderUnknownStartingSegmentsConcreteSyntaxTreeNodeDataChildren
	>;
