import type {BranchConcreteSyntaxTreeNode} from "../../BranchConcreteSyntaxTreeNode.ts";
import type {FunctionHeaderWordStartingSegmentsConcreteSyntaxTreeNodeChildren} from "./FunctionHeaderWordStartingSegmentsConcreteSyntaxTreeNodeChildren.ts";
import type {functionHeaderWordStartingSegmentsConcreteSyntaxTreeNodeTypeName} from "./functionHeaderWordStartingSegmentsConcreteSyntaxTreeNodeTypeName.ts";
export type FunctionHeaderWordStartingSegmentsConcreteSyntaxTreeNode = BranchConcreteSyntaxTreeNode<
	typeof functionHeaderWordStartingSegmentsConcreteSyntaxTreeNodeTypeName,
	FunctionHeaderWordStartingSegmentsConcreteSyntaxTreeNodeChildren
>;
