import type {BranchConcreteSyntaxTreeNode} from "../../../BranchConcreteSyntaxTreeNode.ts";
import type {FunctionCallKnownStartingSegmentsConcreteSyntaxTreeNodeDataChildren} from "./FunctionCallKnownStartingSegmentsConcreteSyntaxTreeNodeDataChildren.ts";
import type {functionCallKnownStartingSegmentsConcreteSyntaxTreeNodeKindName} from "./functionCallKnownStartingSegmentsConcreteSyntaxTreeNodeKindName.ts";
export type FunctionCallKnownStartingSegmentsConcreteSyntaxTreeNode =
	BranchConcreteSyntaxTreeNode<
		typeof functionCallKnownStartingSegmentsConcreteSyntaxTreeNodeKindName,
		FunctionCallKnownStartingSegmentsConcreteSyntaxTreeNodeDataChildren
	>;
